EnterpriseDB/docker-postgresql

- .github/generate-strategy.sh
- update.sh
> Add comments to the pipeline scripts

- README.md
Signed-off-by: Gabriele Bartolini <gabriele.bartolini@enterprisedb.com>
> Fix link to CNP documentation

- update.sh
> Fix typos and remove obsolete variable

- .github/workflows/ci.yml
- Debian/10/Dockerfile
- Debian/10/Dockerfile.postgis
- Debian/11/Dockerfile
- Debian/11/Dockerfile.postgis
- Debian/12/Dockerfile
- Debian/12/Dockerfile.postgis
- Debian/13/Dockerfile
- Debian/13/Dockerfile.postgis
- Debian/Dockerfile-debian.template
- Debian/Dockerfile-postgis.template
- Debian/update.sh
- UBI/10/Dockerfile
- UBI/11/Dockerfile
- UBI/12/Dockerfile
- UBI/13/Dockerfile
- UBI/9.6/Dockerfile
- UBI/Dockerfile.template
- UBI/update.sh
Added the proper labels to the Debian images
The release version now it's properly register
Signed-off-by: Jonathan Gonzalez V <jonathan.gonzalez@enterprisedb.com>
> feat: Added labels and fix others

- .github/generate-strategy.sh
> fix: adjust the naming of PG14 images

- Debian/14/Dockerfile
- Debian/14/Dockerfile.postgis
- Debian/update.sh
- UBI/14/Dockerfile
- UBI/update.sh
> fix: correctly reset the imagereleaseversion after an update of PostgreSQL packages

- .github/workflows/update.yml
> ci: allow cnp-autobot to always push on main

- Debian/10/Dockerfile
- Debian/10/Dockerfile.postgis
- Debian/11/Dockerfile
- Debian/11/Dockerfile.postgis
- Debian/12/Dockerfile
- Debian/12/Dockerfile.postgis
- Debian/13/Dockerfile
- Debian/13/Dockerfile.postgis
- Debian/14/Dockerfile
- Debian/14/Dockerfile.postgis
- Debian/Dockerfile-debian.template
- Debian/Dockerfile-postgis.template
- UBI/10/Dockerfile
- UBI/11/Dockerfile
- UBI/12/Dockerfile
- UBI/13/Dockerfile
- UBI/14/Dockerfile
- UBI/9.6/Dockerfile
- UBI/Dockerfile.template
> fix: empty out the tmp directory

- .github/generate-strategy.sh
- README.md
- UBI/update.sh
> feat: Add multi-arch for v14 on UBI

- UBI/10/Dockerfile.postgis
- UBI/11/Dockerfile.postgis
- UBI/12/Dockerfile.postgis
- UBI/13/Dockerfile.postgis
- UBI/14/Dockerfile.postgis
- UBI/Dockerfile-postgis.template
> fix: add missing yum cache cleanup

- .github/workflows/build.yml
Signed-off-by: Jonathan Gonzalez V <jonathan.gonzalez@enterprisedb.com>
> fix: add `accept-keywords` to dockle scan

- .github/generate-strategy.sh
> ci: fix Debian v15 tags

- .github/workflows/build.yml
> chore: Ignore dockle CIS-DI-0009 checkpoint

- .github/generate-strategy.sh
- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/update.yml
> chore: replace deprecated set-output command

- UBI/10/Dockerfile
- UBI/10/Dockerfile.postgis
- UBI/11/Dockerfile
- UBI/11/Dockerfile.postgis
- UBI/12/Dockerfile
- UBI/12/Dockerfile.postgis
- UBI/13/Dockerfile
- UBI/13/Dockerfile.postgis
- UBI/14/Dockerfile
- UBI/14/Dockerfile.postgis
- UBI/15/Dockerfile
- UBI/15/Dockerfile.postgis
- UBI/Dockerfile-postgis.template
- UBI/Dockerfile.template
> fix: make sure glibc is updated before reinstalling

- .github/workflows/build.yml
- .github/workflows/ci.yml
- UBI/Dockerfile-postgis.template
> ci: remove rhsm-host symlink and set a custom subscription name

- UBI/10/Dockerfile
- UBI/11/Dockerfile
- UBI/12/Dockerfile
- UBI/13/Dockerfile
- UBI/14/Dockerfile
- UBI/15/Dockerfile
- UBI/Dockerfile.template
- UBI/update.sh
> fix: Use CloudSmith  for ppc64le packages

- .github/generate-strategy.sh
- UBI/11/Dockerfile.multiarch
- UBI/12/Dockerfile.multiarch
- UBI/13/Dockerfile.multiarch
- UBI/14/Dockerfile.multiarch
- UBI/15/Dockerfile.multiarch
- UBI/Dockerfile-multiarch.template
- UBI/update.sh
The multiarch images add s390x and ppc64le architectures
> chore: Add a new set of images to add multiarch

- .github/workflows/update.yml
We should only update once a week
> chore: update the images only during Sunday

- UBI/update.sh
This reverts commit e4c3cdac215564e24a37cf83878e99a402be0c54.
> Revert "fix: skip barman version 3.12.0 (#198)"
